/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OurCraftRouteImport } from './routes/our-craft'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsStationeryRouteImport } from './routes/products.stationery'
import { Route as ProductsLeatherJournalsRouteImport } from './routes/products.leather-journals'
import { Route as ProductsLeatherAccessoriesRouteImport } from './routes/products.leather-accessories'
import { Route as ProductsHandmadePaperRouteImport } from './routes/products.handmade-paper'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OurCraftRoute = OurCraftRouteImport.update({
  id: '/our-craft',
  path: '/our-craft',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsStationeryRoute = ProductsStationeryRouteImport.update({
  id: '/stationery',
  path: '/stationery',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsLeatherJournalsRoute = ProductsLeatherJournalsRouteImport.update({
  id: '/leather-journals',
  path: '/leather-journals',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsLeatherAccessoriesRoute =
  ProductsLeatherAccessoriesRouteImport.update({
    id: '/leather-accessories',
    path: '/leather-accessories',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsHandmadePaperRoute = ProductsHandmadePaperRouteImport.update({
  id: '/handmade-paper',
  path: '/handmade-paper',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRoute
  '/our-craft': typeof OurCraftRoute
  '/products': typeof ProductsRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/wholesale': typeof WholesaleRoute
  '/products/handmade-paper': typeof ProductsHandmadePaperRoute
  '/products/leather-accessories': typeof ProductsLeatherAccessoriesRoute
  '/products/leather-journals': typeof ProductsLeatherJournalsRoute
  '/products/stationery': typeof ProductsStationeryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRoute
  '/our-craft': typeof OurCraftRoute
  '/products': typeof ProductsRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/wholesale': typeof WholesaleRoute
  '/products/handmade-paper': typeof ProductsHandmadePaperRoute
  '/products/leather-accessories': typeof ProductsLeatherAccessoriesRoute
  '/products/leather-journals': typeof ProductsLeatherJournalsRoute
  '/products/stationery': typeof ProductsStationeryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRoute
  '/our-craft': typeof OurCraftRoute
  '/products': typeof ProductsRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/wholesale': typeof WholesaleRoute
  '/products/handmade-paper': typeof ProductsHandmadePaperRoute
  '/products/leather-accessories': typeof ProductsLeatherAccessoriesRoute
  '/products/leather-journals': typeof ProductsLeatherJournalsRoute
  '/products/stationery': typeof ProductsStationeryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/journal'
    | '/our-craft'
    | '/products'
    | '/sustainability'
    | '/wholesale'
    | '/products/handmade-paper'
    | '/products/leather-accessories'
    | '/products/leather-journals'
    | '/products/stationery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/journal'
    | '/our-craft'
    | '/products'
    | '/sustainability'
    | '/wholesale'
    | '/products/handmade-paper'
    | '/products/leather-accessories'
    | '/products/leather-journals'
    | '/products/stationery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/journal'
    | '/our-craft'
    | '/products'
    | '/sustainability'
    | '/wholesale'
    | '/products/handmade-paper'
    | '/products/leather-accessories'
    | '/products/leather-journals'
    | '/products/stationery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  JournalRoute: typeof JournalRoute
  OurCraftRoute: typeof OurCraftRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SustainabilityRoute: typeof SustainabilityRoute
  WholesaleRoute: typeof WholesaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-craft': {
      id: '/our-craft'
      path: '/our-craft'
      fullPath: '/our-craft'
      preLoaderRoute: typeof OurCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/stationery': {
      id: '/products/stationery'
      path: '/stationery'
      fullPath: '/products/stationery'
      preLoaderRoute: typeof ProductsStationeryRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/leather-journals': {
      id: '/products/leather-journals'
      path: '/leather-journals'
      fullPath: '/products/leather-journals'
      preLoaderRoute: typeof ProductsLeatherJournalsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/leather-accessories': {
      id: '/products/leather-accessories'
      path: '/leather-accessories'
      fullPath: '/products/leather-accessories'
      preLoaderRoute: typeof ProductsLeatherAccessoriesRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/handmade-paper': {
      id: '/products/handmade-paper'
      path: '/handmade-paper'
      fullPath: '/products/handmade-paper'
      preLoaderRoute: typeof ProductsHandmadePaperRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsHandmadePaperRoute: typeof ProductsHandmadePaperRoute
  ProductsLeatherAccessoriesRoute: typeof ProductsLeatherAccessoriesRoute
  ProductsLeatherJournalsRoute: typeof ProductsLeatherJournalsRoute
  ProductsStationeryRoute: typeof ProductsStationeryRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsHandmadePaperRoute: ProductsHandmadePaperRoute,
  ProductsLeatherAccessoriesRoute: ProductsLeatherAccessoriesRoute,
  ProductsLeatherJournalsRoute: ProductsLeatherJournalsRoute,
  ProductsStationeryRoute: ProductsStationeryRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  JournalRoute: JournalRoute,
  OurCraftRoute: OurCraftRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SustainabilityRoute: SustainabilityRoute,
  WholesaleRoute: WholesaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
